org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

## Mod Properties
minecraft_version=26.2
forge_version=65.1.0
mod_id=totw_modded
mod_version=1.0.9
mod_group_id=net.celsiusqc.totw_modded
