# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml

modLoader="javafml"
loaderVersion="[61,)"
license="All Rights Reserved"

[[mods]]
modId="totw_modded"
version="${file.jarVersion}"
displayName="Towers Of The Wild Modded"
authors="celsiusqc"

description='''Towers of the Wild for modern Minecraft, with datapack-driven tower generation across many biomes.'''

[[dependencies.totw_modded]]
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.totw_modded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,26.1)"
    ordering="NONE"
    side="BOTH"
